@startuml
queue PrincipalStream
card ErrorManagement
queue RetryStream
card RetryManagement
card AnalyticsMonitoring

actor ManualOperation
actor Consumer
queue DelQueueStream
database Database
Consumer --> ErrorManagement : **Error detected**
ErrorManagement --> RetryStream : Can Retry

RetryManagement <-- RetryStream : Consume
RetryManagement --> RetryManagement : Wait
PrincipalStream <-- RetryManagement : Retry

ErrorManagement --> DelQueueStream : Not resolvable
DelQueueStream --> ManualOperation : Consume 
ManualOperation <--> Database : Read and Save
ManualOperation -> RetryStream : Produce
Consumer <-l- PrincipalStream : Consume
RetryStream ---> AnalyticsMonitoring : Analyze
DelQueueStream --->AnalyticsMonitoring : Analyze
AnalyticsMonitoring->ManualOperation : Alert And Monitor
AnalyticsMonitoring -> Database  : Save 
@enduml