@startuml
queue PrincipalStream
card ErrorManagement
queue RetryStream
card RetryManagement
card AnalyticsMonitoring

actor ManualOperation
actor Consumer
queue DelQueueStream
database Database
Consumer --> ErrorManagement : **Error detected**
ErrorManagement --> RetryStream : Retry
RetryManagement --> RetryStream : Retry
RetryManagement --> RetryManagement : Wait
RetryManagement --> DelQueueStream : Retry KO

ErrorManagement --> DelQueueStream : Not resolvable
DelQueueStream -> ManualOperation : Manual 
ManualOperation <--> Database : Read and Save
ManualOperation -> RetryStream : Retry
Consumer <-l- PrincipalStream : Consume
Consumer <- RetryStream  : Consume
RetryStream ---> AnalyticsMonitoring 
DelQueueStream --->AnalyticsMonitoring 
AnalyticsMonitoring->ManualOperation : Alert And Monitor
AnalyticsMonitoring -> Database  : Save Alert
@enduml