@startuml

[*] ---> Detect : Error detected
Detect --> Done : Resolved
Error --> Retry : Retry n times
Retry --> Detect : Try
Detect -> Error : On error

Error -> Wait : Wait before retry
Wait -> Retry : Retry
Error ---> [*] : Not resolved
Done ---> [*] : Message Ok


@enduml
