@startuml

group Kafka Stream Processed
entity RetryStream
entity Offset
entity PrincipalStream

end


control Producer
control Consumer
collections  RetryManager


loop on partition

RetryManager -> Consumer : poll one second
RetryStream <- Consumer : Get Records
RetryStream -> Consumer : Get Records
RetryManager <- Consumer : Get Records
loop on records
	       
    RetryManager -> RetryManager : Get Next Record
    RetryManager -> RetryManager : Is it time ?
    alt successful 
        RetryManager -> Producer : push the payload
        Producer -> PrincipalStream : push the record
        Producer <- PrincipalStream
        RetryManager <- Producer
        RetryManager -> Consumer : Commit Partition
        Consumer -> Offset : push and commit
        Consumer <- Offset 
        RetryManager <- Consumer
    else
        RetryManager->RetryManager: go to the next partition/record
    end
    

end

end



@enduml
